### ISSUE TITLE
Add a GetStatusAsync() method to the Media channel.

### ISSUE THREAD

**Issue by RobertK66** [Tapanila/SharpCaster#303]
Hi,
I found another small improvement: In my main use case I do FireandForget a LoadQueue() and normally I also close the ConGui.exe App after this. When I restart my ConGui.exe now I find the running Application, reconnect and join the session. Volume and Load/LoadQueue work as expected.

But now If I want to operate Prev/Next or any other Media channel operations they fail, because I have no local knowledge about current MediaStatus with the MediaSessionId. But this is needed for all MediaMessages (e.g. Play and Pause)

In order to solve this I added a GetStatusAsync(), which was not there, on the MediaChannel?
```
public async Task<MediaStatus> GetStatusAsync() {
            var chromecastStatus = Client.GetChromecastStatus();
            var message = new Sharpcaster.Messages.Receiver.GetStatusMessage();
            return await SendAsync(message, chromecastStatus.Applications[0]);
}
```
and in the case we rejoin an existing app session, I just called this to get current MediaStatus response and the channel is setup for operation. 
```
 public async Task<ChromecastStatus> LaunchApplicationAsync(string applicationId, bool joinExistingApplicationSession = true)
 {
     if (joinExistingApplicationSession)
     {
         var status = GetChromecastStatus();
         var runningApplication = status?.Applications?.FirstOrDefault(x => x.AppId == applicationId);
         if (runningApplication != null)
         {
             await GetChannel<IConnectionChannel>().ConnectAsync(runningApplication.TransportId);
             await GetChannel<IMediaChannel>().GetStatusAsync();                 // get a running media Session id if there is one
             return await GetChannel<IReceiverChannel>().GetChromecastStatusAsync();
         } 
     }
     var newApplication = await GetChannel<IReceiverChannel>().LaunchApplicationAsync(applicationId);
     await GetChannel<IConnectionChannel>().ConnectAsync(newApplication.Applications.First().TransportId);
     return await GetChannel<IReceiverChannel>().GetChromecastStatusAsync();
 }

```

This implementation is not really clean. I think a better way would be to move it up into the StatusChannel<TResponse> class but as I have not that much time left this and the coming 2 weeks, I was not able to prepare the proper unittests for a new pull request yet.

( Another thing I would like to revisit here is, that I entered the mediaSessionId in the external API of my queue commands. I somehow remember that I needed this in some cases because the 'current status' of the media channel sometimes 'got lost' - overwritten by MEDIA_STATUS messages only containing part of the content !? (i can not reproduce now, maybe we fixed something around this problem. if so we could remove the external buffering of mediaSessionId that I do in my client.... ))

**Comment by RobertK66** [comment]
No prob. It was my try to make a quickfix. Your release 1.1.15 works.

In release 1.1.16 there seems something wrong with the dependencies. I do get a :
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Tmds.MDns, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Tmds.MDns, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null'
   at Sharpcaster.MdnsChromecastLocator..ctor()
   at ConGui.ChromeCastWrapper.StartAsync(CancellationToken cancellationToken) in C:\Users\Robert.RKOSAD\source\repos\HomeAudio\ConGui\ChromeCastWrapper.cs:line 105
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ConGui.Program.Main(String[] args) in C:\Users\Robert.RKOSAD\source\repos\HomeAudio\ConGui\Program.cs:line 51
   at ConGui.Program.<Main>(String[] args)
```
