### ISSUE TITLE
release 1.1.16 broken?

### ISSUE THREAD

**Issue by RobertK66** [Tapanila/SharpCaster#304]
In release 1.1.16 there seems something wrong with the dependencies. I do get a :
```

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Tmds.MDns, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Tmds.MDns, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null'
   at Sharpcaster.MdnsChromecastLocator..ctor()
   at ConGui.ChromeCastWrapper.StartAsync(CancellationToken cancellationToken) in C:\Users\Robert.RKOSAD\source\repos\HomeAudio\ConGui\ChromeCastWrapper.cs:line 105
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ConGui.Program.Main(String[] args) in C:\Users\Robert.RKOSAD\source\repos\HomeAudio\ConGui\Program.cs:line 51
   at ConGui.Program.<Main>(String[] args)
```
and also in nuget package manager view the Tmds.MDns is not shown in 'Transitive packages' as it was done up to release 1.1.15 !?

**Comment by Tapanila** [comment]
I probably broke it with the nuspec file. Will take a look at it

**Comment by Tapanila** [comment]
Yep. Seems like using both .nuspec file and .csproj was causing issues.
Now it's back to using only .csproj but moved all properties that were defined in nuspec to csproj.

So 1.1.17 should work now.

**Comment by RobertK66** [comment]
yes, 👍 works again. thx a lot.
