### ISSUE TITLE
NullReferenceExceptions on ChromecastClient.ConnectChromecast

### ISSUE THREAD

**Issue by PereViader** [Tapanila/SharpCaster#327]
Hello, I seem to have found an issue with the library.

I could not find any root cause for the underlying issue. The error seemingly happens randomly.

I'd really like to use the library in my project any assistance will be greatly appreciated!

`Repro rate:  4/8`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sharpcaster.ChromecastClient.SendAsync(ILogger channelLogger, CastMessage castMessage)
   at Sharpcaster.ChromecastClient.SendAsync(ILogger channelLogger, String ns, IMessage message, String destinationId)
   at Sharpcaster.Channels.ChromecastChannel.SendAsync(IMessage message, String destinationId)
   at Sharpcaster.Channels.ConnectionChannel.ConnectAsync()
   at Sharpcaster.ChromecastClient.ConnectChromecast(ChromecastReceiver chromecastReceiver)
   at PereViader.MusicCaster.MusicService.PlaySong() in C:\Users\perev\Code\MusicCaster\PereViader.MusicCaster\MusicService.cs:line 71
   at PereViader.MusicCaster.MusicService.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\perev\Code\MusicCaster\PereViader.MusicCaster\MusicService.cs:line 28
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at Sharpcaster.ChromecastClient.ConnectChromecast(ChromecastReceiver chromecastReceiver)
         at PereViader.MusicCaster.MusicService.PlaySong() in C:\Users\perev\Code\MusicCaster\PereViader.MusicCaster\MusicService.cs:line 71
         at PereViader.MusicCaster.MusicService.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\perev\Code\MusicCaster\PereViader.MusicCaster\MusicService.cs:line 28
```

`framework: net9.0`
`windows 11`

Source code for MusicService: https://github.com/PereViader/MusicCaster/blob/ea6c54fb76c7fb95f88065e8feadbd09c88a52fa/PereViader.MusicCaster/MusicService.cs
It uses the same code provided as on the readme of this project

In case the information is relevant, there are 25 cast devices on the network
![image](https://github.com/user-attachments/assets/620a704d-dc0a-44ca-98cb-185fc802905f)

The error happens when trying to connect to the group where I want to cast music to.
The group includes 6 of those 25 devices.
Those devices in the group consist of: Nest Mini, Google Home Mini, Nest Hub Max, Pixel Tablet

**Comment by Tapanila** [comment]
Thanks for report. I haven't been able to reproduce the issue. Do you know what's null in those cases where you have the issue?

**Comment by Tapanila** [comment]
This was most probably related to IPv6 issue.
Basically if your network card, router and chromecast support IPv6 sometimes the returned IP of chromecast is IPv6.
I was able to reproduce this around 40% of time (10 requests to same device, from same device and router).

Issue is now fixed on 1.2.3.
If you can reproduce the errors please reopen this issue

**Comment by PereViader** [comment]
Hello @Tapanila, 
Sorry for not coming back earlier with more info on this.
I have updated to the latest version, and it seems like the issue is now completely fixed.
Amazing work.
Thanks a lot!

**Comment by Tapanila** [comment]
Great to hear that it's now fixed and thanks a lot for reporting.
