### ISSUE TITLE
A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. (Exception from HRESULT: 0x800B0109)

### ISSUE THREAD

**Issue by poumason** [tapanila/SharpCaster#65]
at Sockets.Plugin.NativeExceptionExtensions.<>c__DisplayClass0_0.<WrapNativeSocketExceptionsAsTask>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpCaster.Services.ChromecastSocketService.<Initialize>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpCaster.ChromeCastClient.<ConnectChromecast>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

In my project use the Nuget version and new master, when I connect the chromecast v1, always get the exception.

**Comment by tapanila** [comment]
Seems like v1 chromecast has different certificate then v2. I mainly test with v2.

I will look into this. But the fix needs to be done on the socket library which can be found from https://github.com/rdavisau/sockets-for-pcl
So this might take a while to fix.

**Comment by poumason** [comment]
got it. thank you.

**Comment by fabianfoos** [comment]
I did this in ChromecastSocketService.Initialize, but I don't know if it is a good solution.
```
try
{
    await _client.ConnectAsync(host, int.Parse(port), true);
}
catch (Exception)
{
    StreamSocket socket = ((IExposeBackingSocket)_client).Socket as StreamSocket;
    if (socket.Information.ServerCertificateErrorSeverity == SocketSslErrorSeverity.Ignorable && socket.Information.ServerCertificateErrors.Count > 0)
    {
        socket.Control.IgnorableServerCertificateErrors.Clear();
        foreach (ChainValidationResult ignorableError in socket.Information.ServerCertificateErrors)
        {
            socket.Control.IgnorableServerCertificateErrors.Add(ignorableError);
        }

        await _client.ConnectAsync(host, int.Parse(port), true);
    }
}
```
I hope this can help you.

**Comment by tapanila** [comment]
Hey,

I have created a pull requests to solve this but it is not yet merged.
https://github.com/rdavisau/sockets-for-pcl/pull/107

I will soon fork the library and create a new nuget package and switch to that so will get this solver soon.

**Comment by tapanila** [comment]
Sorry that it took so long. Issue is now fixed
